/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EixosRouteImport } from './routes/eixos'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as JovensRouteImport } from './routes/jovens'
import { Route as LoteRouteImport } from './routes/lote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EixosRoute = EixosRouteImport.update({
  id: '/eixos',
  path: '/eixos',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const JovensRoute = JovensRouteImport.update({
  id: '/jovens',
  path: '/jovens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoteRoute = LoteRouteImport.update({
  id: '/lote',
  path: '/lote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eixos' | '/especialidades' | '/jovens' | '/lote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eixos' | '/especialidades' | '/jovens' | '/lote'
  id: '__root__' | '/' | '/eixos' | '/especialidades' | '/jovens' | '/lote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EixosRoute: typeof EixosRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  JovensRoute: typeof JovensRoute
  LoteRoute: typeof LoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eixos': {
      id: '/eixos'
      path: '/eixos'
      fullPath: '/eixos'
      preLoaderRoute: typeof EixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jovens': {
      id: '/jovens'
      path: '/jovens'
      fullPath: '/jovens'
      preLoaderRoute: typeof JovensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lote': {
      id: '/lote'
      path: '/lote'
      fullPath: '/lote'
      preLoaderRoute: typeof LoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EixosRoute: EixosRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  JovensRoute: JovensRoute,
  LoteRoute: LoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
