/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcolhidaRouteImport } from './routes/acolhida'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EixosRouteImport } from './routes/eixos'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as InsigniasRouteImport } from './routes/insignias'
import { Route as JovensRouteImport } from './routes/jovens'
import { Route as LoteRouteImport } from './routes/lote'
import { Route as AdminAcolhidaRouteImport } from './routes/admin.acolhida'
import { Route as AdminEixosRouteImport } from './routes/admin.eixos'
import { Route as AdminEspecialidadesRouteImport } from './routes/admin.especialidades'
import { Route as AdminInsigniasRouteImport } from './routes/admin.insignias'
import { Route as AdminJovensRouteImport } from './routes/admin.jovens'
import { Route as AdminPontuacaoRouteImport } from './routes/admin.pontuacao'
import { Route as AdminPresencaRouteImport } from './routes/admin.presenca'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcolhidaRoute = AcolhidaRouteImport.update({
  id: '/acolhida',
  path: '/acolhida',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EixosRoute = EixosRouteImport.update({
  id: '/eixos',
  path: '/eixos',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const InsigniasRoute = InsigniasRouteImport.update({
  id: '/insignias',
  path: '/insignias',
  getParentRoute: () => rootRouteImport,
} as any)
const JovensRoute = JovensRouteImport.update({
  id: '/jovens',
  path: '/jovens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoteRoute = LoteRouteImport.update({
  id: '/lote',
  path: '/lote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcolhidaRoute = AdminAcolhidaRouteImport.update({
  id: '/acolhida',
  path: '/acolhida',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEixosRoute = AdminEixosRouteImport.update({
  id: '/eixos',
  path: '/eixos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspecialidadesRoute = AdminEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsigniasRoute = AdminInsigniasRouteImport.update({
  id: '/insignias',
  path: '/insignias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJovensRoute = AdminJovensRouteImport.update({
  id: '/jovens',
  path: '/jovens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPontuacaoRoute = AdminPontuacaoRouteImport.update({
  id: '/pontuacao',
  path: '/pontuacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresencaRoute = AdminPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acolhida': typeof AcolhidaRoute
  '/admin': typeof AdminRouteWithChildren
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/insignias': typeof InsigniasRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
  '/admin/acolhida': typeof AdminAcolhidaRoute
  '/admin/eixos': typeof AdminEixosRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/insignias': typeof AdminInsigniasRoute
  '/admin/jovens': typeof AdminJovensRoute
  '/admin/pontuacao': typeof AdminPontuacaoRoute
  '/admin/presenca': typeof AdminPresencaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acolhida': typeof AcolhidaRoute
  '/admin': typeof AdminRouteWithChildren
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/insignias': typeof InsigniasRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
  '/admin/acolhida': typeof AdminAcolhidaRoute
  '/admin/eixos': typeof AdminEixosRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/insignias': typeof AdminInsigniasRoute
  '/admin/jovens': typeof AdminJovensRoute
  '/admin/pontuacao': typeof AdminPontuacaoRoute
  '/admin/presenca': typeof AdminPresencaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acolhida': typeof AcolhidaRoute
  '/admin': typeof AdminRouteWithChildren
  '/eixos': typeof EixosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/insignias': typeof InsigniasRoute
  '/jovens': typeof JovensRoute
  '/lote': typeof LoteRoute
  '/admin/acolhida': typeof AdminAcolhidaRoute
  '/admin/eixos': typeof AdminEixosRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/insignias': typeof AdminInsigniasRoute
  '/admin/jovens': typeof AdminJovensRoute
  '/admin/pontuacao': typeof AdminPontuacaoRoute
  '/admin/presenca': typeof AdminPresencaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acolhida'
    | '/admin'
    | '/eixos'
    | '/especialidades'
    | '/insignias'
    | '/jovens'
    | '/lote'
    | '/admin/acolhida'
    | '/admin/eixos'
    | '/admin/especialidades'
    | '/admin/insignias'
    | '/admin/jovens'
    | '/admin/pontuacao'
    | '/admin/presenca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acolhida'
    | '/admin'
    | '/eixos'
    | '/especialidades'
    | '/insignias'
    | '/jovens'
    | '/lote'
    | '/admin/acolhida'
    | '/admin/eixos'
    | '/admin/especialidades'
    | '/admin/insignias'
    | '/admin/jovens'
    | '/admin/pontuacao'
    | '/admin/presenca'
  id:
    | '__root__'
    | '/'
    | '/acolhida'
    | '/admin'
    | '/eixos'
    | '/especialidades'
    | '/insignias'
    | '/jovens'
    | '/lote'
    | '/admin/acolhida'
    | '/admin/eixos'
    | '/admin/especialidades'
    | '/admin/insignias'
    | '/admin/jovens'
    | '/admin/pontuacao'
    | '/admin/presenca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcolhidaRoute: typeof AcolhidaRoute
  AdminRoute: typeof AdminRouteWithChildren
  EixosRoute: typeof EixosRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  InsigniasRoute: typeof InsigniasRoute
  JovensRoute: typeof JovensRoute
  LoteRoute: typeof LoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acolhida': {
      id: '/acolhida'
      path: '/acolhida'
      fullPath: '/acolhida'
      preLoaderRoute: typeof AcolhidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eixos': {
      id: '/eixos'
      path: '/eixos'
      fullPath: '/eixos'
      preLoaderRoute: typeof EixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insignias': {
      id: '/insignias'
      path: '/insignias'
      fullPath: '/insignias'
      preLoaderRoute: typeof InsigniasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jovens': {
      id: '/jovens'
      path: '/jovens'
      fullPath: '/jovens'
      preLoaderRoute: typeof JovensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lote': {
      id: '/lote'
      path: '/lote'
      fullPath: '/lote'
      preLoaderRoute: typeof LoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acolhida': {
      id: '/admin/acolhida'
      path: '/acolhida'
      fullPath: '/admin/acolhida'
      preLoaderRoute: typeof AdminAcolhidaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eixos': {
      id: '/admin/eixos'
      path: '/eixos'
      fullPath: '/admin/eixos'
      preLoaderRoute: typeof AdminEixosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/especialidades': {
      id: '/admin/especialidades'
      path: '/especialidades'
      fullPath: '/admin/especialidades'
      preLoaderRoute: typeof AdminEspecialidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insignias': {
      id: '/admin/insignias'
      path: '/insignias'
      fullPath: '/admin/insignias'
      preLoaderRoute: typeof AdminInsigniasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jovens': {
      id: '/admin/jovens'
      path: '/jovens'
      fullPath: '/admin/jovens'
      preLoaderRoute: typeof AdminJovensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pontuacao': {
      id: '/admin/pontuacao'
      path: '/pontuacao'
      fullPath: '/admin/pontuacao'
      preLoaderRoute: typeof AdminPontuacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presenca': {
      id: '/admin/presenca'
      path: '/presenca'
      fullPath: '/admin/presenca'
      preLoaderRoute: typeof AdminPresencaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcolhidaRoute: typeof AdminAcolhidaRoute
  AdminEixosRoute: typeof AdminEixosRoute
  AdminEspecialidadesRoute: typeof AdminEspecialidadesRoute
  AdminInsigniasRoute: typeof AdminInsigniasRoute
  AdminJovensRoute: typeof AdminJovensRoute
  AdminPontuacaoRoute: typeof AdminPontuacaoRoute
  AdminPresencaRoute: typeof AdminPresencaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcolhidaRoute: AdminAcolhidaRoute,
  AdminEixosRoute: AdminEixosRoute,
  AdminEspecialidadesRoute: AdminEspecialidadesRoute,
  AdminInsigniasRoute: AdminInsigniasRoute,
  AdminJovensRoute: AdminJovensRoute,
  AdminPontuacaoRoute: AdminPontuacaoRoute,
  AdminPresencaRoute: AdminPresencaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcolhidaRoute: AcolhidaRoute,
  AdminRoute: AdminRouteWithChildren,
  EixosRoute: EixosRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  InsigniasRoute: InsigniasRoute,
  JovensRoute: JovensRoute,
  LoteRoute: LoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
